CREATE DATABASE OFFICE 
go
USE OFFICE
go
CREATE TABLE COMPANY(ID INT PRIMARY KEY IDENTITY,FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),HOMENUMBER VARCHAR(20),
WORKNUMBER VARCHAR(20),PERSONALNUMBER VARCHAR(20))

go

INSERT INTO COMPANY 
VALUES ( 'Luisa', 'Huges', NULL, '920,176,1456', '928,132,2967'),  
( 'Paul', 'Ward', NULL, NULL, '982,132,2867'),  
( 'Rose', 'Huges', NULL, NULL, NULL)  

go

SELECT * FROM COMPANY
--ISNULL
SELECT * FROM COMPANY WHERE WORKNUMBER IS NULL

--NOTNULL

SELECT * FROM COMPANY WHERE WORKNUMBER IS NOT NULL

--COALESCE

SELECT FIRSTNAME +LASTNAME AS FULLNAME, 
coalesce(Worknumber,HomeNumber,Personalnumber,'NA') 
as PhoneNumber FROM COMPANY

go

--CREATE PROCEDURE sp_GetCount(@EmployeeCount INT OUTPUT)
--AS
--BEGIN
--SELECT @EmployeeCount=COUNT(ID)
--FROM EMPLOYEE
--END
--DECLARE @EmployeeTotal int
--EXECUTE  sp_GetCount @EmployeeCount=@EmployeeTotal OUTPUT
--PRINT @EmployeeTotal 